# Generated by Django 4.0.1 on 2022-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precious', '0002_alter_newassetapprovalzone_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='model',
            field=models.CharField(max_length=256, verbose_name='网卡型号'),
        ),
    ]
